#Standardize and add variables to CITES COP participant data,
#then outwrite sample data (for validation) and final data.

##############
####Set Up####
##############

#clear memory
rm( list=ls() )

#Load some packages
library(tm)
library(tidyverse)
library(readxl)
library(stringr)
library(rvest)
library(quanteda)
library(XML)
library(xml2)
library(doBy)
library(reshape2)
library(readxl)

#set seed
set.seed(50)

#set working directory
setwd("")

###################################
#########Read in Raw Data##########
###################################

#read in intermediate data 
raw.data <- read_excel("CITES Extracted Data V2.xlsx")

##########################################
#########Add Additional Variables#########
##########################################

#standardize honorifics
raw.data$Honorific<-ifelse(grepl("^+Dr+$",raw.data$Honorific),"Dr.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+H\\.E+$",raw.data$Honorific),"H.E.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+H\\.E\\.Mr\\.+$",raw.data$Honorific),"H.E. Mr.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+H\\.E\\.Ms\\.+$",raw.data$Honorific),"H.E. Ms.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Ms+$",raw.data$Honorific),"Ms.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Mr+$",raw.data$Honorific),"Mr.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Mr\\.T+$",raw.data$Honorific),"Mr.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Ms\\.T+$",raw.data$Honorific),"Ms.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Ms\\.Y+$",raw.data$Honorific),"Ms.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Prof+$",raw.data$Honorific),"Prof.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Prof\\. Dr\\.+$",raw.data$Honorific),"Prof.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+sr\\.+$",raw.data$Honorific),"Sr.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Professor+$",raw.data$Honorific),"Prof.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Miss+$",raw.data$Honorific),"Ms.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+M\\. S\\.+$",raw.data$Honorific),"M.",raw.data$Honorific)
raw.data$Honorific<-ifelse(grepl("^+Mme+$",raw.data$Honorific),"Mme.",raw.data$Honorific)

#standardize Status varaible
raw.data$Status<-ifelse(grepl("INTERGOVERNMENTAL ORGANIZATIONS",raw.data$Status),"Intergovernmental Organizations",raw.data$Status)
raw.data$Status<-ifelse(grepl("NON-GOVERNMENTAL ORGANIZATIONS",raw.data$Status),"Non-Governmental Organizations",raw.data$Status)
raw.data$Status<-ifelse(grepl("UNITED NATIONS AND ITS SPECIALIZED AGENCIES",raw.data$Status),"United Nations and its Specialized Agencies",raw.data$Status)
raw.data$Status<-ifelse(grepl("OBSERVERS",raw.data$Status),"Observers",raw.data$Status)
raw.data$Status<-ifelse(grepl("PRIVATE SECTOR",raw.data$Status),"Private Sector",raw.data$Status)
raw.data$Status<-ifelse(grepl("Party",raw.data$Status),"Parties",raw.data$Status)
raw.data$Status<-ifelse(grepl("Observer+$",raw.data$Status),"Observers",raw.data$Status)
raw.data$Status<-ifelse(grepl("Obsevers+$",raw.data$Status),"Observers",raw.data$Status)

#create indicator variables for party and observer
raw.data$Party<-0
raw.data$Observer<-0
raw.data$Party[raw.data$Status=="Parties"]<-1
raw.data$Observer[raw.data$Status!="Parties"]<-1

#fix delegation entries 
raw.data$Delegation<-gsub("S Tate Of","State Of",raw.data$Delegation)
raw.data$Delegation<- gsub("\\(U\\.k\\.\\)$", "United Kingdom", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(U\\.s\\.a\\.\\)$", "(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(U\\.s\\.a\\. \\)$", "(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(Usa\\)$", "(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(U\\.s\\. A\\.\\)$", "(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(United States Of America\\)$","(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(United States America\\)$","(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(United States of America\\)$","(U.S.A.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(F\\.r\\. Germany\\)$", "(F.R.G.)", raw.data$Delegation)
raw.data$Delegation<- gsub("\\(F\\.r\\.g\\.\\)$", "(F.R.G.)", raw.data$Delegation)
raw.data$Delegation<- gsub("(?<!,) Inc\\.$", ", Inc.",raw.data$Delegation, perl = TRUE)
raw.data$Delegation<- gsub("(?<!,) Inc$", ", Inc.",raw.data$Delegation, perl = TRUE)
raw.data$Delegation<- gsub(", Inc$", ", Inc.",raw.data$Delegation, perl = TRUE)
raw.data$Delegation<- gsub("\\(Italy, Italia, Italie\\)$", "(Italy)", raw.data$Delegation)
raw.data$Delegation<- gsub(" Of ", " of ", raw.data$Delegation)
raw.data$Delegation<- gsub(" And ", " and ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Des ", " des ", raw.data$Delegation)
raw.data$Delegation<- gsub(" De ", " de ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Y ", " y ", raw.data$Delegation)
raw.data$Delegation<- gsub(" E ", " e ", raw.data$Delegation)
raw.data$Delegation<- gsub(" For ", " for ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Pour ", " pour ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Por ", " por ", raw.data$Delegation)
raw.data$Delegation<- gsub(" The ", " the ", raw.data$Delegation)
raw.data$Delegation<- gsub(" El ", " el ", raw.data$Delegation)
raw.data$Delegation<- gsub(" La ", " la ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Los ", " los ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Las ", " las ", raw.data$Delegation)
raw.data$Delegation<- gsub("Industrial Цacion","Industrialización",raw.data$Delegation)
raw.data$Delegation<- gsub("Industrializacion ","Industrialización",raw.data$Delegation)
raw.data$Delegation<- gsub("Industrializacion_de","Industrialización de",raw.data$Delegation)
raw.data$Delegation<- gsub("Comercializacion ","Comercialización ",raw.data$Delegation)
raw.data$Delegation<- gsub("Comerciálizacion ","Comercialización ",raw.data$Delegation)
raw.data$Delegation<- gsub("\\(Vet\\.ezuela\\)$","(Venezuela)",raw.data$Delegation)

#standardize country names
raw.data$Delegation<-ifelse(grepl("\\(Italie\\)",raw.data$Delegation),"(Italy)",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Antigua And Barbuda Y Barbuda+$",raw.data$Delegation),"Antigua and Barbuda",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Ariana+$",raw.data$Delegation),"Turkey",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Bolivia \\(Plurinational State of\\)+$",raw.data$Delegation),"Bolivia",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Cape Verde+$",raw.data$Delegation),"Cabo Verde",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Cameroon, United Republic of+$",raw.data$Delegation),"Cameroon",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Central African Republic Centroafricana Centrafricaine+$",raw.data$Delegation),"Central African Republic",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Central African Republic]+$",raw.data$Delegation),"Central African Republic",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Czech Republic Checa Tchèque+$",raw.data$Delegation),"Czech Republic",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Democratic Republic of The Congo Democrática Del Congo Démocratique Du Congo+$",raw.data$Delegation),"Democratic Republic if The Congo",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Zaire+$",raw.data$Delegation),"Democratic Republic of The Congo",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Dominican Republic Dominicaine+$",raw.data$Delegation),"Dominican Republic",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Equatorial Guinea Ecuatorial Équatoriale+$",raw.data$Delegation),"Equatorial Guinea",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Swaziland+$",raw.data$Delegation),"Eswatini",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Guatamala+$",raw.data$Delegation),"Guatemala",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Iran, Islamic Republic of+$",raw.data$Delegation),"Iran",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Iran \\(Islamic Republic of\\)+$",raw.data$Delegation),"Iran",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Iran \\(Islamic Republic of\\) \\(República Islámica Del\\) \\(République Islamique D'\\)+$",raw.data$Delegation),"Iran",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Jordán+$",raw.data$Delegation),"Jordan",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Libyan Arab Jamahiriya+$",raw.data$Delegation),"Libya",raw.data$Delegation)  
raw.data$Delegation<-ifelse(grepl("^+Lisboa Republic of Korea+$",raw.data$Delegation),"Republic of Korea",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+New Zealand Zelandia+$",raw.data$Delegation),"New Zealand",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Pákistan+$",raw.data$Delegation),"Pakistan",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Netherland+$",raw.data$Delegation),"Netherlands",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Netherlands Bajos+$",raw.data$Delegation),"Netherlands",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Papua New Guinea Nueva Guinea+$",raw.data$Delegation),"Papua New Guinea",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Russian Federation De Rusia De Russie+$",raw.data$Delegation),"Russian Federation",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Saint Vincent And The Grenadines+$",raw.data$Delegation),"Saint-Vincent And The Grenadines",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Saint Vincent And The Grenadines Vicente Y Las Granadinas Grenadines+$",raw.data$Delegation),"Saint-Vincent And The Grenadines",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Saint Lucia Lucia+$",raw.data$Delegation),"Saint Lucia",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Saint Lucia Lucía+$",raw.data$Delegation),"Saint Lucia",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Saint Kitts And Nevis Kitts Y Nieves+$",raw.data$Delegation),"Saint Kitts And Nevis",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Republic of Moldova+$",raw.data$Delegation),"Moldova",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Saudi Arabia Saudita Saoudite+$",raw.data$Delegation),"Saudi Arabia",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Serbia Y Montenegro+$",raw.data$Delegation),"Serbia",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Sierra Leone Leona+$",raw.data$Delegation),"Sierra Leone",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Singapore Wong+$",raw.data$Delegation),"Singapore",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+South Africa Du Sud+$",raw.data$Delegation),"South Africa",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Surináme+$",raw.data$Delegation),"Suriname",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Swedan+$",raw.data$Delegation),"Sweden",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Tanzania, United Republic of Republique-Unie De+$",raw.data$Delegation),"Tanzania, United Republic Of",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+United Republic of Tanzania+$",raw.data$Delegation),"Tanzania, United Republic Of",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+United Republic of Tanzania Unida De Tanzanía De Tanzanie+$",raw.data$Delegation),"Tanzania, United Republic Of",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Trinidad And Tob Ago+$",raw.data$Delegation),"Trinidad And Tobago",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+Trinidad And Tobago Y Tabago+$",raw.data$Delegation),"Trinidad And Tobago",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+United Arab Emirates Árabes Unidos Arabes Unis+$",raw.data$Delegation),"United Arab Emirates",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+United Kingdom Unido+$",raw.data$Delegation),"United Kingdom",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+United Kingdom of Great Britain and Northern Ireland+$",raw.data$Delegation),"United Kingdom",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+United Kingdom of Great Britain and Northern Ireland Unido De Gran Bretaña E Irlanda Del Norte Uni De Grande-Bretagne Et D'irlande Du Nord+$",raw.data$Delegation),"United Kingdom",raw.data$Delegation)   
raw.data$Delegation<-ifelse(grepl("^+United States of Ámerica+$",raw.data$Delegation),"United States of America",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+United States of America D’amerique Unidos De America+$",raw.data$Delegation),"United States of America",raw.data$Delegation)  
raw.data$Delegation<-ifelse(grepl("^+United States of Ámerica Unidos De America+$",raw.data$Delegation),"United States of America",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+United States of America Unidos De América D'amérique+$",raw.data$Delegation),"United States of America",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Venezuela \\(Bolivarian Republic Of\\)+$",raw.data$Delegation),"Venezuela",raw.data$Delegation)    
raw.data$Delegation<-ifelse(grepl("^+Venezuela \\(Bolivian Republic Of\\)+$",raw.data$Delegation),"Venezuela",raw.data$Delegation)  
raw.data$Delegation<-ifelse(grepl("^+German Democratic Republic Democratique Allemande Democratica Alemana+$",raw.data$Delegation),"German Democratic Republic",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+German Democratic Republic Democratique Allemande Democratica Alemana+$",raw.data$Delegation),"German Democratic Republic",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Germany, Federal Republic of+$",raw.data$Delegation),"Germany",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Germany, Federal Republic of Federale D’allemagne Federal De Alemania+$",raw.data$Delegation),"Germany",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Germany, Federal Republic of Republiąue Federale De+$",raw.data$Delegation),"Germany",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Cambia+$",raw.data$Delegation),"Gambia",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+El S Alvador+$",raw.data$Delegation),"El Salvador",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Republic Of+$",raw.data$Delegation),"Moldova",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Republic of Korea+$",raw.data$Delegation),"Republic of Korea",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Korea+$",raw.data$Delegation),"Republic of Korea",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Republic of Korea De Corea De Corée+$",raw.data$Delegation),"Republic of Korea",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+\\(Bolívia \\)+$",raw.data$Delegation),"(Bolivia)",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Yugoslavia+$",raw.data$Delegation),"Serbia",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Vicuna \\(Condortips Sa\\) \\(Peru+$",raw.data$Delegation),"Vicuna (Condortips Sa) (Peru)",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Royal Society For The Protection of Birds \\(United Kingdom Unido\\)+$",raw.data$Delegation),"Royal Society For The Protection Of Birds (United Kingdom)",raw.data$Delegation) 
raw.data$Delegation<-ifelse(grepl("^+Pet Trade And Industry Association Ltd \\(United Kingdom Unido\\)+$",raw.data$Delegation),"Pet Trade And Industry Association Ltd (United Kingdom)",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+M\\. A\\. C\\. A\\. \\(Bolívia \\)+$",raw.data$Delegation),"M. A. C. A. (Bolivia)",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Kazakstan+$",raw.data$Delegation),"Kazakhstan",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+Côte D'ivoire+$",raw.data$Delegation),"Cote D'ivoire",raw.data$Delegation)
raw.data$Delegation<-ifelse(grepl("^+\\(Italy\\)+$",raw.data$Delegation),"Unione Nazionale Industria Conciaria (Italy)",raw.data$Delegation)

raw.data$Delegation<- gsub(" Of ", " of ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Of$", " of", raw.data$Delegation)
raw.data$Delegation<- gsub(" And ", " and ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Des ", " des ", raw.data$Delegation)
raw.data$Delegation<- gsub(" De ", " de ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Y ", " y ", raw.data$Delegation)
raw.data$Delegation<- gsub(" E ", " e ", raw.data$Delegation)
raw.data$Delegation<- gsub(" For ", " for ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Pour ", " pour ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Por ", " por ", raw.data$Delegation)
raw.data$Delegation<- gsub(" The ", " the ", raw.data$Delegation)
raw.data$Delegation<- gsub(" El ", " el ", raw.data$Delegation)
raw.data$Delegation<- gsub(" La ", " la ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Los ", " los ", raw.data$Delegation)
raw.data$Delegation<- gsub(" Las ", " las ", raw.data$Delegation)
raw.data$Delegation<-gsub("Côte D'ivoire","Côte d'Ivoire",raw.data$Delegation)
raw.data$Delegation<-gsub("Cote D'ivoire","Côte d'Ivoire",raw.data$Delegation)

#Add COW and then ISO country codes to State delegations
raw.data$Delegation_COW<-NA
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Afghanistan",700,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Albania",339,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Algeria",615,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Andorra",232,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Angola",540,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Antigua and Barbuda",58,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Argentina",160,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Armenia",371,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Australia",900,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Austria",305,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Azerbaijan",373,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bahamas",31,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bahrain",692,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bangladesh",771,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Barbados",53,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Belarus",370,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Belgium",211,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Belize",80,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Benin",434,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bhutan",760,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bolivia",145,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bosnia and Herzegovina",346,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Botswana",571,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Brazil",140,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Brunei Darussalam",835,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Bulgaria",355,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Burkina Faso",439,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Burundi",516,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cabo Verde",402,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cambodia",811,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cameroon",471,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Canada",20,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Central African Republic",482,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Chad",483,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Chile",155,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="China",710,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Colombia",100,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Comoros",581,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Congo",484,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cook Islands", NA, raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Costa Rica",94,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Côte d'Ivoire",437,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Croatia",344,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cuba",40,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Cyprus",352,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Czech Republic",316,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Czechoslovakia",315,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Democratic People's Republic of Korea",731,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Democratic Republic of the Congo",490,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Denmark",390,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Djibouti",522,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Dominica",54,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Dominican Republic",42,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Ecuador",130,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Egypt",651,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="El Salvador",92,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Equatorial Guinea",411,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Eritrea",531,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Estonia",366,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Ethiopia",530,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="European Community",NA,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="European Union",NA,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Fiji",950,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Finland",375,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="France",220,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Gabon",481,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Gambia",420,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Georgia",372,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Germany",255,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="German Democratic Republic",265,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Ghana",452,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Greece",350,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Grenada",55,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Guatemala",90,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Guinea",438,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Guinea-Bissau",404,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Guyana",110,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Haiti",41,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Holy See",NA,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Honduras",91,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Hungary",310,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Iceland",395,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="India",750,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Indonesia",850,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Iran",630,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Iraq",645,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Ireland",205,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Israel",666,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Italy",325,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Jamaica",51,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Japan",740,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Jordan",663,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Kazakhstan",705,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Kenya",501,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Kiribati",946,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Kuwait",690,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Kyrgyzstan",703,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Lao People's Democratic Republic",812,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Latvia",367,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Lebanon",660,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Lesotho",570,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Liberia",450,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Libya",620,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Liechtenstein",223,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Lithuania",368,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Luxembourg",212,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Madagascar",580,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Malawi",553,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Malaysia",820,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Maldives",781,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mali",432,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Malta",338,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Marshall Islands",983,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mauritania",435,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mauritius",590,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mexico",70,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Micronesia (Federated States of)",987,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Micronesia (Federated States Of)",987,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Moldova",359,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Monaco",221,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mongolia",712,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Montenegro",341,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Morocco",600,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Mozambique",541,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Myanmar",775,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Namibia",565,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Nauru",970,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Nepal",790,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Netherlands",210,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="New Zealand",920,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Nicaragua",93,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Niger",436,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Nigeria",475,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Niue",NA,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Norway",385,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Oman",698,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Pakistan",770,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Palau",986,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Palestine",NA,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Panama",95,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Papua New Guinea",910,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Paraguay",150,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Peru",135,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Philippines",840,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Poland",290,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Portugal",235,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Qatar",694,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Republic of Korea",732,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Romania",360,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Russian Federation",365,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Rwanda",517,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Saint Kitts and Nevis",60,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Saint Lucia",56,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Saint-Vincent and the Grenadines",57,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Samoa",990,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="San Marino",331,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Sao Tome and Principe",403,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Saudi Arabia",670,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Senegal",433,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Serbia",345,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Seychelles",591,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Sierra Leone",451,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Singapore",830,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Slovakia",317,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Slovenia",349,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Solomon Islands",940,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Somalia",520,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="South Africa",560,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="South Sudan",626,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Spain",230,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Sri Lanka",780,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Sudan",625,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Suriname",115,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Eswatini",572,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Sweden",380,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Switzerland",225,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Syrian Arab Republic",652,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Tajikistan",702,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Thailand",800,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="North Macedonia",343,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Timor-Leste",860,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Togo",461,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Tonga",955,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Trinidad and Tobago",52,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Tunisia",616,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Turkey",640,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Turkmenistan",701,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Tuvalu",947,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Uganda",500,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Ukraine",369,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Union of Soviet Socialist Republics",365,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="United Arab Emirates",696,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="United Kingdom",200,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Tanzania, United Republic of",510,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="United States of America",2,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Uruguay",165,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Uzbekistan",704,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Vanuatu",935,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Venezuela",101,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Viet Nam",817,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Yemen",679,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Yugoslavia",345,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Zambia",551,raw.data$Delegation_COW)
raw.data$Delegation_COW<-ifelse(raw.data$Delegation=="Zimbabwe",552,raw.data$Delegation_COW)
raw.data$Delegation_COW<-round(raw.data$Delegation_COW)

raw.data$Delegation_ISO<-NA
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Afghanistan","AFG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Albania","ALB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Algeria","DZA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Andorra","AND",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Angola","AGO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Antigua and Barbuda","ATG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Argentina","ARG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Armenia","ARM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Australia","AUS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Austria","AUT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Azerbaijan","AZE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bahamas","BHS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bahrain","BHR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bangladesh","BGD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Barbados","BRB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Belarus","BLR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Belgium","BEL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Belize","BLZ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Benin","BEN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bhutan","BTN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bolivia","BOL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bosnia and Herzegovina","BIH",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Botswana","BWA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Brazil","BRA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Brunei Darussalam","BRN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Bulgaria","BGR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Burkina Faso","BFA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Burundi","BDI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cabo Verde","CPV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cambodia","KHM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cameroon","CMR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Canada","CAN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Central African Republic","CAF",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Chad","TCD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Chile","CHL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="China","CHN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Colombia","COL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Comoros","COM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Congo","COG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cook Islands", "COK", raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Costa Rica","CRI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Côte d'Ivoire","CIV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Croatia","HRV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cuba","CUB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Cyprus","CYP",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Czech Republic","CZE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Czechoslovakia","CSK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Democratic People's Republic of Korea","PRK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Democratic Republic of the Congo","COD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Denmark","DNK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Djibouti","DJI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Dominica","DMA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Dominican Republic","DOM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Ecuador","ECU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Egypt","EGY",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="El Salvador","SLV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Equatorial Guinea","GNQ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Eritrea","ERI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Estonia","EST",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Ethiopia","ETH",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="European Community",NA,raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="European Union","EUE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Fiji","FJI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Finland","FIN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="France","FRA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Gabon","GAB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Gambia","GMB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Georgia","GEO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Germany","DEU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="German Democratic Republic","DDR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Ghana","GHA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Greece","GRC",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Grenada","GRD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Guatemala","GTM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Guinea","GIN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Guinea-Bissau","GNB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Guyana","GUY",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Haiti","HTI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Holy See","VAT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Honduras","HND",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Hungary","HUN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Iceland","ISL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="India","IND",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Indonesia","IDN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Iran","IRN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Iraq","IRQ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Ireland","IRL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Israel","ISR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Italy","ITA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Jamaica","JAM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Japan","JPN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Jordan","JOR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Kazakhstan","KAZ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Kenya","KEN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Kiribati","KIR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Kuwait","KWT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Kyrgyzstan","KGZ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Lao People's Democratic Republic","LAO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Latvia","LVA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Lebanon","LBN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Lesotho","LSO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Liberia","LBR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Libya","LBY",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Liechtenstein","LIE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Lithuania","LTU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Luxembourg","LUX",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Madagascar","MDG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Malawi","MWI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Malaysia","MYS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Maldives","MDV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mali","MLI",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Malta","MLT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Marshall Islands","MHL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mauritania","MRT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mauritius","MUS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mexico","MEX",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Micronesia (Federated States of)","FSM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Micronesia (Federated States Of)","FSM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Moldova","MDA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Monaco","MCO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mongolia","MNG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Montenegro","MNE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Morocco","MAR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Mozambique","MOZ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Myanmar","MMR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Namibia","NAM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Nauru","NRU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Nepal","NPL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Netherlands","NLD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="New Zealand","NZL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Nicaragua","NIC",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Niger","NER",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Nigeria","NGA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Niue","NIU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Norway","NOR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Oman","OMN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Pakistan","PAK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Palau","PLW",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Palestine","PSE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Panama","PNA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Papua New Guinea","PNG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Paraguay","PRY",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Peru","PER",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Philippines","PHL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Poland","POL",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Portugal","PRT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Qatar","QAT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Republic of Korea","KOR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Romania","ROU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Russian Federation","RUS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Rwanda","RWA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Saint Kitts and Nevis","KNA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Saint Lucia","LCA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Saint-Vincent and the Grenadines","VCT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Samoa","WSM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="San Marino","SMR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Sao Tome and Principe","STP",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Saudi Arabia","SAU",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Senegal","SEN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Serbia","SRB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Seychelles","SYC",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Sierra Leone","SLE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Singapore","SGP",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Slovakia","SVK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Slovenia","SVN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Solomon Islands","SLB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Somalia","SOM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="South Africa","ZAF",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="South Sudan","SSD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Spain","ESP",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Sri Lanka","LKA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Sudan","SDN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Suriname","SUR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Eswatini","SWZ",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Sweden","SWE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Switzerland","CHE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Syrian Arab Republic","SYR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Tajikistan","TJK",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Thailand","THA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="North Macedonia","MKD",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Timor-Leste","TLS",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Togo","TGO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Tonga","TON",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Trinidad and Tobago","TTO",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Tunisia","TUN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Turkey","TUR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Turkmenistan","TKM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Tuvalu","TUV",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Uganda","UGA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Ukraine","UKR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Union of Soviet Socialist Republics","SUN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="United Arab Emirates","ARE",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="United Kingdom","GBR",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Tanzania, United Republic of","TZA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="United States of America","USA",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Uruguay","URY",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Uzbekistan","UZB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Vanuatu","VUT",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Venezuela","VEN",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Viet Nam","VNM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Yemen","YEM",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Yugoslavia","YUG",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Zambia","ZMB",raw.data$Delegation_ISO)
raw.data$Delegation_ISO<-ifelse(raw.data$Delegation=="Zimbabwe","ZWE",raw.data$Delegation_ISO)


#rename some varaibles
raw.data <- subset(raw.data, select = -c(DelegationCOW, DelegationISO))
colnames(raw.data)<-c("CoP","CoPyear","CoPcity","Status","Delegation","URL","Honorific","PersonID","Affiliation","AffiliationStatus","CoPlatitude",       "CoPlongitude","Latitude","Longitude","GeoPrecision","Distance","Party","Observer","Female","Male","DelegationCOW","DelegationISO")    

#save final data
write.csv(raw.data,"cites.cops.csv",row.names=FALSE,fileEncoding = "UTF-8")

#randomly sample rows for spatial validation
set.seed(123) 
table(raw.data$Affiliation=="NA")
nrow(raw.data)
original.data<-raw.data
raw.data<-subset(raw.data,(Affiliation!="NA"))
random_rows_indices <- sample(nrow(raw.data), 1000)
sampled_data <- raw.data[random_rows_indices, ]

#save spatial validation data
write.csv(sampled_data,"spatialvalidation.csv",row.names=FALSE,fileEncoding = "UTF-8")

